// <auto-generated />
using System;
using MatrioshkaBookingSystem.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MatrioshkaBookingSystem.Migrations
{
    [DbContext(typeof(BookingDbContext))]
    partial class BookingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_0900_ai_ci")
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");
            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Assetsinroom", b =>
                {
                    b.Property<int>("RoomId")
                        .HasColumnType("int")
                        .HasColumnName("RoomID");

                    b.Property<int>("AssetId")
                        .HasColumnType("int")
                        .HasColumnName("AssetID");

                    b.HasKey("RoomId", "AssetId")
                        .HasName("PRIMARY")
                        .HasAnnotation("MySql:IndexPrefixLength", new[] { 0, 0 });

                    b.HasIndex(new[] { "AssetId" }, "AssetID");

                    b.ToTable("assetsinrooms", (string)null);
                });

            modelBuilder.Entity("MatrioshkaBookingSystem.Models.Billinginfo", b =>
                {
                    b.Property<int>("BillingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("BillingID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("BillingId"));

                    b.Property<string>("CardNumber")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("BillingId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "UserId" }, "UserID");

                    b.ToTable("billinginfo", (string)null);
                });

            modelBuilder.Entity("MatrioshkaBookingSystem.Models.Booking", b =>
                {
                    b.Property<int>("BookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("BookingID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("BookingId"));

                    b.Property<int?>("BillingId")
                        .HasColumnType("int")
                        .HasColumnName("BillingID");

                    b.Property<DateOnly>("DateofBooking")
                        .HasColumnType("date");

                    b.Property<DateOnly>("EndofBooking")
                        .HasColumnType("date");

                    b.Property<int?>("RoomId")
                        .HasColumnType("int")
                        .HasColumnName("RoomID");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("BookingId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "BillingId" }, "BillingID");

                    b.HasIndex(new[] { "RoomId" }, "RoomID");

                    b.HasIndex(new[] { "UserId" }, "UserID")
                        .HasDatabaseName("UserID1");

                    b.ToTable("bookings", (string)null);
                });

            modelBuilder.Entity("MatrioshkaBookingSystem.Models.Bookingextraasset", b =>
                {
                    b.Property<int>("BookingId")
                        .HasColumnType("int")
                        .HasColumnName("BookingID");

                    b.Property<int>("ExtraAssetId")
                        .HasColumnType("int")
                        .HasColumnName("ExtraAssetID");

                    b.Property<decimal>("ExtraAssetPrice")
                        .HasPrecision(10)
                        .HasColumnType("decimal(10)");

                    b.HasKey("BookingId", "ExtraAssetId")
                        .HasName("PRIMARY")
                        .HasAnnotation("MySql:IndexPrefixLength", new[] { 0, 0 });

                    b.HasIndex(new[] { "ExtraAssetId" }, "ExtraAssetID");

                    b.ToTable("bookingextraassets", (string)null);
                });

            modelBuilder.Entity("MatrioshkaBookingSystem.Models.Extraasset", b =>
                {
                    b.Property<int>("ExtraAssetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ExtraAssetID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ExtraAssetId"));

                    b.Property<decimal>("AssetPrice")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("ExtraAssetName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("ExtraAssetStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("enum('Working','Under Maintenance','Damaged')")
                        .HasDefaultValueSql("'Working'");

                    b.HasKey("ExtraAssetId")
                        .HasName("PRIMARY");

                    b.ToTable("extraassets", (string)null);
                });

            modelBuilder.Entity("MatrioshkaBookingSystem.Models.Floor", b =>
                {
                    b.Property<int>("FloorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("FloorID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("FloorId"));

                    b.Property<int>("FloorNumber")
                        .HasColumnType("int");

                    b.Property<string>("FloorStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("enum('Available','Non-Available')")
                        .HasDefaultValueSql("'Available'");

                    b.Property<int>("HotelId")
                        .HasColumnType("int")
                        .HasColumnName("HotelID");

                    b.HasKey("FloorId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "HotelId" }, "HotelID");

                    b.ToTable("floors", (string)null);
                });

            modelBuilder.Entity("MatrioshkaBookingSystem.Models.Hotel", b =>
                {
                    b.Property<int>("HotelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("HotelID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("HotelId"));

                    b.Property<string>("HotelLocation")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("HotelName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("HotelStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("enum('Open','Closed','Under Maintenance')")
                        .HasDefaultValueSql("'Open'");

                    b.Property<string>("ImagePath")
                        .HasColumnType("longtext");

                    b.HasKey("HotelId")
                        .HasName("PRIMARY");

                    b.ToTable("hotels", (string)null);
                });

            modelBuilder.Entity("MatrioshkaBookingSystem.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RoleID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("RoleId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "RoleName" }, "RoleName")
                        .IsUnique();

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("MatrioshkaBookingSystem.Models.Room", b =>
                {
                    b.Property<int>("RoomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RoomID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("RoomId"));

                    b.Property<int>("FloorId")
                        .HasColumnType("int")
                        .HasColumnName("FloorID");

                    b.Property<string>("RoomStatus")
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<int>("TypeId")
                        .HasColumnType("int")
                        .HasColumnName("TypeID");

                    b.HasKey("RoomId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "FloorId" }, "FloorID");

                    b.HasIndex(new[] { "TypeId" }, "TypeID");

                    b.ToTable("rooms", (string)null);
                });

            modelBuilder.Entity("MatrioshkaBookingSystem.Models.Roomasset", b =>
                {
                    b.Property<int>("AssetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("AssetID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("AssetId"));

                    b.Property<string>("AssetName")
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("AssetStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("enum('Working','Under Maintenance','Damaged')")
                        .HasDefaultValueSql("'Working'");

                    b.HasKey("AssetId")
                        .HasName("PRIMARY");

                    b.ToTable("roomassets", (string)null);
                });

            modelBuilder.Entity("MatrioshkaBookingSystem.Models.Roomtype", b =>
                {
                    b.Property<int>("TypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("TypeID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("TypeId"));

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<decimal>("TypePrice")
                        .HasPrecision(10)
                        .HasColumnType("decimal(10)");

                    b.HasKey("TypeId")
                        .HasName("PRIMARY");

                    b.ToTable("roomtype", (string)null);
                });

            modelBuilder.Entity("MatrioshkaBookingSystem.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("UserPassword")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("UserId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Username" }, "Username")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("UserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("User_ID");

                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("RoleID");

                    b.HasKey("UserId", "RoleId")
                        .HasName("PRIMARY")
                        .HasAnnotation("MySql:IndexPrefixLength", new[] { 0, 0 });

                    b.HasIndex(new[] { "RoleId" }, "RoleID");

                    b.ToTable("user_roles", (string)null);
                });

            modelBuilder.Entity("Assetsinroom", b =>
                {
                    b.HasOne("MatrioshkaBookingSystem.Models.Roomasset", null)
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("assetsinrooms_ibfk_2");

                    b.HasOne("MatrioshkaBookingSystem.Models.Room", null)
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("assetsinrooms_ibfk_1");
                });

            modelBuilder.Entity("MatrioshkaBookingSystem.Models.Billinginfo", b =>
                {
                    b.HasOne("MatrioshkaBookingSystem.Models.User", "User")
                        .WithMany("Billinginfos")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("billinginfo_ibfk_1");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MatrioshkaBookingSystem.Models.Booking", b =>
                {
                    b.HasOne("MatrioshkaBookingSystem.Models.Billinginfo", "Billing")
                        .WithMany("Bookings")
                        .HasForeignKey("BillingId")
                        .HasConstraintName("bookings_ibfk_3");

                    b.HasOne("MatrioshkaBookingSystem.Models.Room", "Room")
                        .WithMany("Bookings")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("bookings_ibfk_2");

                    b.HasOne("MatrioshkaBookingSystem.Models.User", "User")
                        .WithMany("Bookings")
                        .HasForeignKey("UserId")
                        .HasConstraintName("bookings_ibfk_1");

                    b.Navigation("Billing");

                    b.Navigation("Room");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MatrioshkaBookingSystem.Models.Bookingextraasset", b =>
                {
                    b.HasOne("MatrioshkaBookingSystem.Models.Booking", "Booking")
                        .WithMany("Bookingextraassets")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("bookingextraassets_ibfk_1");

                    b.HasOne("MatrioshkaBookingSystem.Models.Extraasset", "ExtraAsset")
                        .WithMany("Bookingextraassets")
                        .HasForeignKey("ExtraAssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("bookingextraassets_ibfk_2");

                    b.Navigation("Booking");

                    b.Navigation("ExtraAsset");
                });

            modelBuilder.Entity("MatrioshkaBookingSystem.Models.Floor", b =>
                {
                    b.HasOne("MatrioshkaBookingSystem.Models.Hotel", "Hotel")
                        .WithMany("Floors")
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("floors_ibfk_1");

                    b.Navigation("Hotel");
                });

            modelBuilder.Entity("MatrioshkaBookingSystem.Models.Room", b =>
                {
                    b.HasOne("MatrioshkaBookingSystem.Models.Floor", "Floor")
                        .WithMany("Rooms")
                        .HasForeignKey("FloorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("rooms_ibfk_1");

                    b.HasOne("MatrioshkaBookingSystem.Models.Roomtype", "Type")
                        .WithMany("Rooms")
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("rooms_ibfk_2");

                    b.Navigation("Floor");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("UserRole", b =>
                {
                    b.HasOne("MatrioshkaBookingSystem.Models.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("user_roles_ibfk_2");

                    b.HasOne("MatrioshkaBookingSystem.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("user_roles_ibfk_1");
                });

            modelBuilder.Entity("MatrioshkaBookingSystem.Models.Billinginfo", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("MatrioshkaBookingSystem.Models.Booking", b =>
                {
                    b.Navigation("Bookingextraassets");
                });

            modelBuilder.Entity("MatrioshkaBookingSystem.Models.Extraasset", b =>
                {
                    b.Navigation("Bookingextraassets");
                });

            modelBuilder.Entity("MatrioshkaBookingSystem.Models.Floor", b =>
                {
                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("MatrioshkaBookingSystem.Models.Hotel", b =>
                {
                    b.Navigation("Floors");
                });

            modelBuilder.Entity("MatrioshkaBookingSystem.Models.Room", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("MatrioshkaBookingSystem.Models.Roomtype", b =>
                {
                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("MatrioshkaBookingSystem.Models.User", b =>
                {
                    b.Navigation("Billinginfos");

                    b.Navigation("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
